/*


 * created by 		:		Shiva RV
 * Date				:		11-25-2018
 * Description		:		This class contains static hard coded values needed in the org

  
*/
public class StaticValueClass {

    public static List<String> allImageFileNames= new List<String>{
        'fish','frog','cat','dog','butterfly', //1
        'lion','wolf','buffalo','ox','tiger', //2
        'elephant','panda','bear','peacock','peahen', //3
        'hen','cock','zebra','horse','rhinoceros', //4
        'hippopotamus','monkey','giraffe','squirrel','pigeon',//5
        'donkey','camel','kangaroo','goat','chick', //6
        'crocodile','deer','alligator','eagle','snake',//7
        'shark','fox','jackal','toad' ,'hyena', //8
        'leopard','cheetah','rabbit','hornet','ostrich',//9
        'owl','parrot','porcupine','pig','rat'    
        
    };
}